services:
  database:
    container_name: database
    image: postgres:17.0
    restart: "no"
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 3s
      start_period: 30s
    volumes:
      - ./db:/var/lib/postgresql/data
