# Generated by Django 4.2.9 on 2024-10-31 13:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('futuboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroupuser',
            name='usergroupuserid',
            field=models.UUIDField(default=uuid.uuid4, null=True, serialize=False),
        ),

    ]
