# Generated by Django 4.2.9 on 2024-11-07 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futuboard', '0004_auto_20241031_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='columnid',
            field=models.ForeignKey(db_column='columnID', on_delete=django.db.models.deletion.CASCADE, to='futuboard.column'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='actionid',
            field=models.ForeignKey(blank=True, db_column='actionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='futuboard.action'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='boardid',
            field=models.ForeignKey(blank=True, db_column='boardID', null=True, on_delete=django.db.models.deletion.CASCADE, to='futuboard.board'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='ticketid',
            field=models.ForeignKey(blank=True, db_column='ticketID', null=True, on_delete=django.db.models.deletion.CASCADE, to='futuboard.ticket'),
        ),
        migrations.AlterField(
            model_name='usergroupuser',
            name='usergroupid',
            field=models.ForeignKey(db_column='usergroupID', on_delete=django.db.models.deletion.CASCADE, to='futuboard.usergroup'),
        ),
        migrations.AlterField(
            model_name='usergroupuser',
            name='userid',
            field=models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='futuboard.user'),
        ),
    ]
