# Generated by Django 4.2.9 on 2024-11-15 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futuboard', '0005_alter_ticket_columnid_alter_usergroup_actionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='swimlanecolumnid',
            field=models.ForeignKey(blank=True, db_column='swimlaneColumnID', null=True, on_delete=django.db.models.deletion.CASCADE, to='futuboard.swimlanecolumn'),
        ),
        migrations.AlterField(
            model_name='action',
            name='ticketid',
            field=models.ForeignKey(blank=True, db_column='ticketID', null=True, on_delete=django.db.models.deletion.CASCADE, to='futuboard.ticket'),
        ),
        migrations.AlterField(
            model_name='column',
            name='boardid',
            field=models.ForeignKey(db_column='boardID', on_delete=django.db.models.deletion.CASCADE, to='futuboard.board'),
        ),
        migrations.AlterField(
            model_name='swimlanecolumn',
            name='columnid',
            field=models.ForeignKey(blank=True, db_column='columnID', null=True, on_delete=django.db.models.deletion.CASCADE, to='futuboard.column'),
        ),
    ]
