# Generated by Django 4.2.9 on 2024-11-19 15:32

import uuid
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("futuboard", "0006_alter_action_swimlanecolumnid_alter_action_ticketid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usergroup",
            name="actionid",
        ),
        migrations.RemoveField(
            model_name="usergroup",
            name="boardid",
        ),
        migrations.RemoveField(
            model_name="usergroup",
            name="ticketid",
        ),
        migrations.AlterUniqueTogether(
            name="usergroupuser",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="usergroupuser",
            name="usergroupid",
        ),
        migrations.RemoveField(
            model_name="usergroupuser",
            name="userid",
        ),
        migrations.AddField(
            model_name="user",
            name="actions",
            field=models.ManyToManyField(to="futuboard.action"),
        ),
        migrations.AddField(
            model_name="user",
            name="boardid",
            field=models.ForeignKey(
                db_column="boardID",
                default=uuid.uuid4,
                on_delete=django.db.models.deletion.CASCADE,
                to="futuboard.board",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="tickets",
            field=models.ManyToManyField(to="futuboard.ticket"),
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="Usergroup",
        ),
        migrations.DeleteModel(
            name="UsergroupUser",
        ),
    ]
