# Generated by Django 4.2.9 on 2024-11-20 11:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("futuboard", "0007_remove_usergroup_actionid_remove_usergroup_boardid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="color",
        ),
        migrations.RemoveField(
            model_name="board",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="column",
            name="color",
        ),
        migrations.RemoveField(
            model_name="swimlanecolumn",
            name="color",
        ),
        migrations.RemoveField(
            model_name="user",
            name="color",
        ),
    ]
