# Generated by Django 4.2.9 on 2025-01-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("futuboard", "0008_remove_action_color_remove_board_creator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="background_color",
            field=models.TextField(default="#ffffff"),
        ),
    ]
