# Generated by Django 4.2.9 on 2025-01-14 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('futuboard', '0008_remove_action_color_remove_board_creator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTemplate',
            fields=[
                ('boardtemplateid', models.UUIDField(db_column='boardTemplateID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='boardTemplates')),
            ],
            options={
                'db_table': 'BoardTemplate',
            },
        ),
    ]
