# Generated by Django 4.2.9 on 2025-01-14 22:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('futuboard', '0008_remove_action_color_remove_board_creator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTemplate',
            fields=[
                ('boardtemplateid', models.UUIDField(db_column='boardTemplateID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='boardTemplates')),
                ('boardid', models.ForeignKey(db_column='boardID', on_delete=django.db.models.deletion.DO_NOTHING, to='futuboard.board')),
            ],
            options={
                'db_table': 'BoardTemplate',
            },
        ),
    ]
