# Generated by Django 4.2.9 on 2025-01-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futuboard', '0008_remove_action_color_remove_board_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='default_ticket_color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='default_ticket_cornernote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='default_ticket_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='default_ticket_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='default_ticket_storypoints',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='default_ticket_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
