# Generated by Django 4.2.9 on 2025-01-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futuboard', '0009_alter_board_boardid_boardtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='background_color',
            field=models.TextField(default='#ffffff'),
        ),
    ]
