# Generated by Django 4.2.9 on 2025-01-14 22:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('futuboard', '0009_boardtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='boardid',
            field=models.UUIDField(db_column='boardID', default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
