# Generated by Django 4.2.9 on 2025-02-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("futuboard", "0010_board_default_ticket_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="background_color",
            field=models.TextField(default="#ffffff"),
        ),
    ]
