# Generated by Django 4.2.9 on 2025-02-11 13:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('futuboard', '0011_board_background_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='default_ticket_storypoints',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='storypoints',
        ),
        migrations.AlterField(
            model_name='action',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='board',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='column',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cornernote',
            field=models.TextField(db_column='cornerNote', default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('ticketeventid', models.UUIDField(db_column='ticketEventID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('ADD', 'ADD'), ('DELETE', 'DELETE'), ('UPDATE', 'UPDATE')], max_length=6)),
                ('title', models.TextField()),
                ('size', models.IntegerField()),
                ('columnid', models.ForeignKey(db_column='columnID', on_delete=django.db.models.deletion.CASCADE, to='futuboard.column')),
            ],
            options={
                'db_table': 'TicketEvent',
            },
        ),
    ]
