# Generated by Django 4.2.9 on 2025-02-16 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("futuboard", "0013_alter_column_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardtemplate",
            name="boardid",
            field=models.ForeignKey(
                db_column="boardID", on_delete=django.db.models.deletion.CASCADE, to="futuboard.board"
            ),
        ),
        migrations.AlterField(
            model_name="ticketevent",
            name="new_columnid",
            field=models.ForeignKey(
                db_column="newColumnId",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="new_columnid",
                to="futuboard.column",
            ),
        ),
        migrations.AlterField(
            model_name="ticketevent",
            name="old_columnid",
            field=models.ForeignKey(
                db_column="oldColumnId",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="old_columnid",
                to="futuboard.column",
            ),
        ),
    ]
