# Generated by Django 4.2.9 on 2025-03-12 20:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("futuboard", "0015_add_ticket_create_event_to_all_tickets"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scope",
            fields=[
                (
                    "scopeid",
                    models.UUIDField(db_column="scopeID", default=uuid.uuid4, primary_key=True, serialize=False),
                ),
                ("title", models.TextField()),
                ("creation_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("forecast_set_date", models.DateTimeField(blank=True, null=True)),
                ("forecast_size", models.IntegerField(blank=True, null=True)),
                (
                    "boardid",
                    models.ForeignKey(
                        db_column="boardID", on_delete=django.db.models.deletion.CASCADE, to="futuboard.board"
                    ),
                ),
                ("done_columns", models.ManyToManyField(to="futuboard.column")),
                ("forecast_tickets", models.ManyToManyField(related_name="forecast_tickets", to="futuboard.ticket")),
                ("tickets", models.ManyToManyField(to="futuboard.ticket")),
            ],
            options={
                "db_table": "Scope",
            },
        ),
        migrations.AddField(
            model_name="ticketevent",
            name="new_scopes",
            field=models.ManyToManyField(related_name="new_scopes", to="futuboard.scope"),
        ),
        migrations.AddField(
            model_name="ticketevent",
            name="old_scopes",
            field=models.ManyToManyField(related_name="old_scopes", to="futuboard.scope"),
        ),
    ]
