# Generated by Django 4.2.9 on 2025-03-12 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("futuboard", "0016_alter_ticketevent_event_type_scope_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scope",
            name="forecast_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scope",
            name="forecast_tickets",
            field=models.ManyToManyField(related_name="forecast_tickets", to="futuboard.ticket"),
        ),
        migrations.AlterField(
            model_name="scope",
            name="scopeid",
            field=models.UUIDField(db_column="scopeID", default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
