# Generated by Django 4.2.9 on 2025-03-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("futuboard", "0016_alter_ticketevent_event_type_scope_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="notes",
            field=models.TextField(default=""),
        ),
    ]
