name: Prettier style check

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Run Prettier
        run: cd frontend && npm run prettier
